[package]
name = "tari_merlin"
version = "4.0.0"
authors = ["The Tari Development Community"]
edition = "2024"
readme = "README.md"
license = "MIT"
repository = "https://github.com/tari-project/merlin"
homepage = "https://docs.rs/merlin"
documentation = "https://docs.rs/merlin"
categories = ["cryptography"]
keywords = ["cryptography", "zero-knowledge", "fiat-shamir", "transcript"]
description = "Composable proof transcripts for public-coin arguments of knowledge"
exclude = [".travis.yml", ".gitignore"]

[package.metadata.docs.rs]
# We need nightly to build docs
features = ["nightly"]

[dependencies]
keccak = { version = "0.1.0", default-features = false }
byteorder = { version = "1.2.4", default-features = false }
zeroize = { version = "1", default-features = false, features = ["zeroize_derive"] }
rand_core = { version = "0.10.1", default-features = false }
hex = {version = "0.3", default-features = false, optional = true}

[dev-dependencies]
strobe-rs = "0.5"
curve25519-dalek = { version = "5.0.0-pre.6", features = ["rand_core"] }
rand_chacha = "0.10"

[features]
default = ["std"]
nightly = []
debug-transcript = ["hex"]
std = ["byteorder/std"]
